# https://nicolas-van.github.io/easy-markdown-to-github-pages/
theme: jekyll-theme-cayman
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - README_.md
  - awesome-gan-inversion.md
  - content/cv-lab.md
  - content/dataset.md
  - content/image-generation.md
  - content/image-restoration.md